import React, { useState, useEffect } from 'react';
import { Activity, CircleDollarSign, PackageCheck, Heart, ExternalLink } from 'lucide-react';
import AdminLayout from '../../components/admin/AdminLayout';
import { authApi } from '../../api/authApi';

export default function AdminDashboard() {
  const [loading, setLoading] = useState(true);
  const [stats, setStats] = useState<any>(null);

  useEffect(() => {
    window.scrollTo(0, 0);
    const fetchStatusValues = async () => {
      try {
        const responseData = await authApi.getDashboardStats();
        
        // 🛠️ FRONTEND INTERCEPT: Transforming backend keys to match UI needs
        const transformedData = {
          totalSales: responseData?.totalRevenue || 0, // Maps backend totalRevenue -> totalSales
          totalOrders: responseData?.totalOrders || 0,  
          productsCount: responseData?.totalProducts || 0, // Maps backend totalProducts -> productsCount
          messagesCount: responseData?.messagesCount || 0, // Graceful fallback
          
          // Fallback structure so the .entries loop doesn't crash on undefined
          salesByCategory: responseData?.salesByCategory || {
            "Herbal Soaps": 0,
            "Essential Oils": 0,
            "Gift Boxes": 0,
            "Souvenirs": 0
          }
        };

        setStats(transformedData);
      } catch (err) {
        console.error("Dashboard stats retrieval error:", err);
      } finally {
        setLoading(false);
      }
    };
    fetchStatusValues();
  }, []);

  if (loading) {
    return (
      <div className="min-h-screen bg-[#0C0B0A] text-brand-cream flex items-center justify-center font-sans-poppins text-xs uppercase tracking-[0.25em] text-brand-gold">
         Siphoning Atelier Stats...
      </div>
    );
  }

  return (
    <AdminLayout
      title="Atelier Insights Dashboard"
      subtitle="Exquisite statistics describing order values, product counts, and revenue curves generated by verified global collectors."
    >
      <div className="space-y-8 font-sans-inter text-left">
        
        {/* Core Stats Bento Cards Grid */}
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
          
          {/* Card 1: Total Revenue */}
          <div className="bg-[#141211] border border-brand-cream/10 p-6 rounded-2xl flex flex-col justify-between space-y-4">
            <div className="flex items-center justify-between">
              <span className="text-[10px] uppercase tracking-widest text-brand-cream/45 font-sans-poppins font-bold">Patron Gross Sales</span>
              <CircleDollarSign className="h-5 w-5 text-brand-gold" />
            </div>
            <div>
              <span className="text-[10px] text-brand-gold uppercase tracking-[0.2em] font-sans-poppins font-medium block">Total Value</span>
              <h3 className="font-serif-playfair text-3xl font-bold font-semibold text-brand-cream mt-1 font-serif-cormorant">
                ₹{stats?.totalSales || 0}
              </h3>
            </div>
            <span className="text-[9px] text-[#A3E635] flex items-center space-x-1 font-sans-poppins">
              <span>●</span> <span>Real-time billing cleared</span>
            </span>
          </div>

          {/* Card 2: Orders Count */}
          <div className="bg-[#141211] border border-brand-cream/10 p-6 rounded-2xl flex flex-col justify-between space-y-4">
            <div className="flex items-center justify-between">
              <span className="text-[10px] uppercase tracking-widest text-brand-cream/45 font-sans-poppins font-bold">Orders Registry</span>
              <Activity className="h-5 w-5 text-brand-gold" />
            </div>
            <div>
              <span className="text-[10px] text-brand-gold uppercase tracking-[0.2em] font-sans-poppins font-medium block">Cleared Orders</span>
              <h3 className="font-serif-playfair text-3xl font-bold font-semibold text-brand-cream mt-1">
                {stats?.totalOrders || 0}
              </h3>
            </div>
            <span className="text-[9px] text-brand-cream/45 font-sans-inter font-light">
              Pending and Dispatched statuses
            </span>
          </div>

          {/* Card 3: Products cured Count */}
          <div className="bg-[#141211] border border-brand-cream/10 p-6 rounded-2xl flex flex-col justify-between space-y-4">
            <div className="flex items-center justify-between">
              <span className="text-[10px] uppercase tracking-widest text-brand-cream/45 font-sans-poppins font-bold">Catalog Registries</span>
              <PackageCheck className="h-5 w-5 text-brand-gold" />
            </div>
            <div>
              <span className="text-[10px] text-brand-gold uppercase tracking-[0.2em] font-sans-poppins font-medium block">Cured Items</span>
              <h3 className="font-serif-playfair text-3xl font-bold font-semibold text-brand-cream mt-1">
                {stats?.productsCount || 0}
              </h3>
            </div>
            <span className="text-[9px] text-brand-cream/45 font-sans-inter font-light">
              Active formulations listed
            </span>
          </div>

          {/* Card 4: Support ticket messages count */}
          <div className="bg-[#141211] border border-brand-cream/10 p-6 rounded-2xl flex flex-col justify-between space-y-4">
            <div className="flex items-center justify-between">
              <span className="text-[10px] uppercase tracking-widest text-brand-cream/45 font-sans-poppins font-bold">Pending Messages</span>
              <Heart className="h-5 w-5 text-brand-gold" />
            </div>
            <div>
              <span className="text-[10px] text-brand-gold uppercase tracking-[0.2em] font-sans-poppins font-medium block">Concierge Tickets</span>
              <h3 className="font-serif-playfair text-3xl font-bold font-semibold text-brand-cream mt-1">
                {stats?.messagesCount || 0}
              </h3>
            </div>
            <span className="text-[9px] text-brand-cream/45 font-sans-inter font-light">
              Guest inquiries to respond
            </span>
          </div>

        </div>

        {/* Categories bento and support links list splits */}
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
          
          {/* LEFT: Category curve breakdown list */}
          <div className="lg:col-span-6 bg-[#141211] border border-brand-cream/10 p-6 sm:p-8 rounded-[2rem] space-y-6">
            <div>
              <h4 className="font-serif-playfair text-xl text-brand-gold font-medium">Bespoke Sales Category Division</h4>
              <p className="text-[11px] text-brand-cream/45 font-light mt-0.5">Estimated gross values divided across categories</p>
            </div>

            <div className="space-y-4">
              {stats?.salesByCategory && Object.entries(stats.salesByCategory).map(([cat, val]: any) => (
                <div key={cat} className="space-y-1.5 uppercase tracking-widest text-[10px] font-sans-poppins">
                  <div className="flex justify-between items-center text-brand-cream/70">
                    <span>{cat} Selection</span>
                    <span className="font-mono text-brand-gold font-bold">₹{val}</span>
                  </div>
                  {/* Decorative Progress bar */}
                  <div className="h-1.5 w-full bg-[#1F1E1D] rounded-full overflow-hidden">
                    <div 
                      className="h-full bg-brand-gold rounded-full transition-all duration-700" 
                      style={{ width: `${Math.min(100, (val / Math.max(1, stats.totalSales)) * 100)}%` }} 
                    />
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* RIGHT: Quick Administrative Tasks Panel */}
          <div className="lg:col-span-6 bg-[#141211] border border-brand-cream/10 p-6 sm:p-8 rounded-[2rem] space-y-6">
            <div>
              <h4 className="font-serif-playfair text-xl text-brand-gold font-medium">Atelier Quick Actions</h4>
              <p className="text-[11px] text-brand-cream/45 font-light mt-0.5">System operations dashboard links</p>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 font-sans-poppins">
              <a 
                href="/admin/products"
                className="p-4 bg-[#1F1D1C] hover:bg-[#2A2726] border border-brand-cream/5 hover:border-brand-gold/30 rounded-xl flex items-center justify-between text-xs font-bold uppercase tracking-wider text-brand-cream transition-all group"
              >
                <span>Curate Catalog Items</span>
                <ExternalLink className="h-4 w-4 text-brand-gold group-hover:translate-x-0.5 transition-transform" />
              </a>

              <a 
                href="/admin/orders"
                className="p-4 bg-[#1F1D1C] hover:bg-[#2A2726] border border-brand-cream/5 hover:border-brand-gold/30 rounded-xl flex items-center justify-between text-xs font-bold uppercase tracking-wider text-brand-cream transition-all group"
              >
                <span>Process Orders Queue</span>
                <ExternalLink className="h-4 w-4 text-brand-gold group-hover:translate-x-0.5 transition-transform" />
              </a>
            </div>

            <div className="pt-4 border-t border-brand-cream/5 text-[10px] text-brand-cream/35">
               Note: System logs are encrypted and stored inside sandbox memory arrays. Please deploy persistent MongoDB adapters for production releases.
            </div>
          </div>

        </div>

      </div>
    </AdminLayout>
  );
}